apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample
  name: sample
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app: sample
  type: NodePort
